### ISSUE TITLE
Flash the firmware to both slots

### ISSUE THREAD

**Issue by MartinX3** [newflasher/newflasher#29]
Dear @munjeni please make it possible to flash both slots in one flashing run.

It is important for the custom ROMs based on sony open devices project to have the newest firmware files on both slots.

The flashtool implemented it now, but I prefer newflasher. :)

**Comment by munjeni** [comment]
Hi, is it safe? I didn't see git commits on flashtool about flashing booth slots at the same time, can you point me to the right direction? I can add an prompt like I done for flashing persist sin file, but what about sin files with string _other_ ? Its flashed to diferent slots when e.g. curront slot is a _other_ is flashed to slot b and vice versa, see https://github.com/newflasher/newflasher/blob/master/newflasher.c#L1729 can it be safe to flash other to booth slots?

**Comment by MartinX3** [comment]
Hey 
The commits are here
https://github.com/Androxyde/devices/pull/98
https://github.com/Androxyde/devices/pull/99
https://github.com/Androxyde/devices/pull/100
I hope they explain enough :)

**Comment by munjeni** [comment]
I can add prompt e.g. press 'a' for sot a, press 'b' for slot 'b' instead of auto slot detection, in that case you would be abble to repeat flashing in order to flash to another slot. Is that enought? I no want make newflasher to flash booth slots in the same time since it will mess newflasher and probably many users will flash system_other to system partition or in worst case brick their phone, newflasher must be keept simple.

**Comment by MartinX3** [comment]
is it possible to write "all" if you want to flash both partitions?
so you don't execute it by accident and only people will do it who know what they do.
So we devs could as example get a coffee and come back with both slots flashed. :)

**Comment by munjeni** [comment]
Its complicated because of e.g. system_other, its flashed always to diferent slot. E.g. is current slot is 'a', system is flashed to 'a' but system_other is flashed to slot 'b' always. So if you flash booth system_other will owerwrite system and vice versa. I no want to complicate newflasher, it must be keept simple. Implem,entation ca be done simple by making prompt 'a' or 'b' instead of autodetection, in that case you would be abble to flash to slot choice but not in booth, in order to flash to another slot you would need to set another slot in next flashing. Its what I can implement. Again I'm sorry I no want to complicate newflshaer.

**Comment by kholk** [comment]
You keep the same structure for flashing. The system_other partition always gets flashed to the "other" slot. If current the current slot is A, then system_other goes on system_b. If current slot is B, then system_other goes on system_a.

You just have to replicate the commits that have been done in the FSC scripts, aka flashing XBL, bluetooth, dsp, modem, rdimage ALWAYS on both A and B slots.

**Comment by munjeni** [comment]
Only that five?

**Comment by munjeni** [comment]
Fully Implemented https://github.com/newflasher/newflasher/commit/196bcf9d63fcc75f384b41d1900030e66d4bf4ea

**Comment by kholk** [comment]
Should be fine. Though, I don't get why are you giving a choice, since that's a totally safe thing to do :D

**Comment by munjeni** [comment]
Nwflasher is based on usb sniff log, I just found that sony didn't flash booth slots and I didn;t implemented too. Can you tell me why this 5 things need to be on booth sloots?

**Comment by kholk** [comment]
Let's say that you are not on a stock ROM and let's say that you have a custom Android system.
Your custom Android system implements A/B OTA, so, when an update is available, like a stock ROM, it installs the newly downloaded OTA on the other slot seamlessly from Android itself: this will switch your slot from A to B or vice versa. 

After you switch your slot, your phone will load not only the OS from the newly selected slot, but also the other things, for example, it will load the bootloader that is present on that slot, with the firmwares present on that slot. 

If you flash a new stock firmware, the modem, for example, or one of the other firmwares may be incompatible with an old bootloader (and that's why you need to flash all this stuff along with bootloader on both slots). 

Regarding the bootloader itself, which is reason #1, on the Tama platform, the first release has a bad bug regarding slot B: this will be unable to boot a custom kernel image due to signature verification failing (the OEM unlock state is respected only on slot A in this case!).
New bootloader releases are addressing this bug.

Now, you get that, if you flash the new bootloader only on slot A, you will still have the bug on slot B!

That's not the only reason to update the xbl on both slots: there are many other reasons that I will not explain in order to stop writing an entire book on updates here on github :P

**Comment by munjeni** [comment]
Its clean, thank you! I'm clossing this.
