### ISSUE TITLE
Bootloop problem with Xperia 5ii

### ISSUE THREAD

**Issue by wydy** [newflasher/newflasher#40]
```
Hi, this is not newflasher isue, Mark 2 devices faces rollback protection, more info about it read this https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/post-84077083 . Further questions please ask in forum.
```
_Originally posted by @munjeni in https://github.com/newflasher/newflasher/issues/39#issuecomment-745279730_

Sorry for disturbing, but that issue is closed and I am not sure whether my reply could be seen in previous issue.
It seems that it isn’t a rollback problem because I have use the newer version firmware. Since my original version is 58.0.A.28.17 and the version I have flashed is 58.0.A.28.60.

I have tried flashing older version to generate a rollback problem, and found that the fault appearance is quite different.
If there is a rollback problem, the device will shows 'Your device is corrupt' instead of bootloops

My english is not very good. My apologize for not clearly describing the problem in the previous issue.

**Comment by munjeni** [comment]
This is not newflasher isue! We can speak on forum, not here. You should try switch to slot A and try reflash. Also read page 72 https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/page-72 there is some info we have discovered recently and I will not repeat it again just read it and try it byself.

Bootloop related to rollback protection:
----------------------------------------------------
The gist of the feature is that it’ll prevent your phone from booting if it detects that the device was downgraded to an earlier, now unapproved version of software that has been deemed insecure because of a security vulnerability. A slightly more technical explanation is that the VBMeta data structure, which holds the hash for the boot partition and hashtree metadatas for system and vendor partitions, uses a rollback index to reject images that have an older rollback index.

Thats part of this https://www.xda-developers.com/android-pie-rollback-protection/?_ga=2.172732451.1057106755.1607978449-524393242.1607978449

Don't open another issue since github isues is for real isues only, and since this is not newflasher isue you should continue in forum if you need to ask something

**Comment by munjeni** [comment]
One who reported https://github.com/newflasher/newflasher/issues/37 issue had boot loop instead of device corupted, and we have discovered (after getting bootloader boot log) that it is rollback protection isue (or maybe fw isue I don't know), but bootloader log clearly states about problem:

load_and_verify_vbmeta:657: ERROR: vbmeta_a: Image rollback index is less than the stored rollback index.

You can open thread on xda xperia 5 II forum and ask somebody. Newflsher apsolutly have nothing to do with it. Even no single error or warning trought newflasher, so no newflasher isue.
