### ISSUE TITLE
Question/Suggestion for persist partition flashing prompt

### ISSUE THREAD

**Issue by leewp14** [newflasher/newflasher#41]
Hi there, first of all, thanks for the efforts made in creating this tool. 
I'm a new user, and this is also my first time flashing a newer model Xperia, Xperia XZ1. 
I did a flashing on my unit, and after a lengthy, very long flashing process, it asked whether I wanted to flash persist partition. 
So, I don't know about it and I copied the url, read everything in the thread, and decided not to flash persist. 
However when I switch back to the CMD, it came up in my mind that it was written something like "Press Y to skip flashing persist.sin", so I pressed Y. 
Immediately I noticed that it started to flash persist.sin. I immediately reach out for the usb port but I hesitated because I don't know if I interrupt the process, will my device get a hard brick. I just bought this device. 
Therefore, I decided to let the flashing continue. And very sad, extremely sad, I confirmed that the attestation key is completely gone. 

I thank you for implementing the warning, not blaming you because I'm extremely exhausted at that time so I was extremely careless. Just I would like to provide suggestions so maybe other users can avoid carelessness like me. 
1. Maybe make the skip option as the first option in the sentences, because it reads that it is recommended to skip but the not to skip option comes first, then only followed by the skip option. 
2. Or maybe, I actually prefer this more, is that ask this before flashing process starts (along with the other prompts like the backup ta and driver stuff). With this, maybe can also add a prompt to confirm flashing so we can actually still cancel if we press the wrong key before start flashing the device. 
3. Since this is quite crucial, maybe make it to type something longer instead of just a single letter, like for example, 'n' to skip  persist but 'yes' to flash persist
4. Make the warning a bit scary, like upper case texts, or some scary disclaimer, or something like FLASH AT YOUR OWN RISK! I AM NOT RESPONSIBLE FOR YOUR ATTESTATION KEY LOST!
5. Also, just asking, if we pressed Y, and it started to flash, at which flash stage it is still safe to disconnect the device to avoid persist.sin to be flashed?

I would like to express that I'm not blaming the dev! I really thankful the warning is given and actually get to understand it before answering the prompt. It's just my carelessness. So I would like to provide suggestion in order to help avoid this. I actually read through your threads and get to know the amount of effort put into this newflasher and the xflasher. Thanks for the contribution!

Thanks and have a nice day!

**Comment by munjeni** [comment]
Hi, yes I know how frustrating is when something happen wrong, but next time please be a more carefull. Warning message during flashing is easy enought to warn user, even I have included url link so everybody who see a warning prompt can read url first before confirm with Y or N. This is a primitive tool - simple as possible - just for primitive flashing, its not a smart tool which will do the auto things for you, and I not going to make it smart, its smart enought just for flashing, everybody who use them must be carefull and patient, and you can't interupt flashing when you disconnect usb because if you do that e.g. while you flash bootloader your device will become dead. The same for persist partition, you disconnected usb but it not helped. You must be more carefull next time.

**Comment by munjeni** [comment]
Further replies please reply to forum https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/ this is development platform not a forum, thanks!
